from docx import Document
from docx.shared import Pt, Inches
from pathlib import Path
from ..llm import LLM

class DOCXGenerator:
    def __init__(self):
        self.llm = LLM()

    def generate(self, output_path, prompt, source_text="", existing=None):
        fallback = {
            "title":"Editra AI Document",
            "sections":[
                {"heading":"Overview","paragraphs":[
                    "This document was generated by Editra AI.",
                    f"User instruction: {prompt}"
                ]}
            ]
        }
        content = self.llm.json(
            """Create structured document content. Return JSON only:
{"title":"...", "sections":[{"heading":"...","paragraphs":["..."]}]}.
Write professional, useful content and do not invent unsupported facts when source text is supplied.""",
            f"REQUEST:\n{prompt}\nSOURCE:\n{source_text[:18000]}",
            fallback
        )
        doc = Document()
        sec = doc.sections[0]
        sec.top_margin, sec.bottom_margin = Inches(.7), Inches(.7)
        doc.add_heading(content["title"], 0)
        for s in content.get("sections", []):
            doc.add_heading(s.get("heading","Section"), 1)
            for para in s.get("paragraphs", []):
                doc.add_paragraph(para)
        doc.save(output_path)
        return output_path
