from pptx import Presentation
from pptx.util import Inches, Pt
from ..llm import LLM

class PPTXGenerator:
    def __init__(self):
        self.llm = LLM()

    def generate(self, output_path, prompt, source_text="", template_path=None, existing=None):
        prs = Presentation(template_path) if template_path else Presentation()
        fallback = {
            "title":"Editra AI Presentation",
            "slides":[
                {"title":"Overview","bullets":[
                    "Editable presentation generated by Editra AI.",
                    f"Request: {prompt}"
                ]}
            ]
        }
        content = self.llm.json(
            """Create a presentation outline. Return JSON only:
{"title":"...", "slides":[{"title":"...","bullets":["..."]}]}.
Keep bullets concise and presentation-ready.""",
            f"REQUEST:\n{prompt}\nSOURCE:\n{source_text[:18000]}",
            fallback
        )
        # For a template, append new slides while preserving the template's theme/layout.
        # For a blank deck, use a standard title-and-content layout.
        layout = prs.slide_layouts[1] if len(prs.slide_layouts) > 1 else prs.slide_layouts[0]
        for s in content.get("slides", []):
            slide = prs.slides.add_slide(layout)
            slide.shapes.title.text = s.get("title","")
            body = slide.placeholders[1] if len(slide.placeholders) > 1 else None
            if body:
                tf = body.text_frame
                tf.clear()
                for i, bullet in enumerate(s.get("bullets", [])):
                    p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
                    p.text = bullet
                    p.level = 0
        prs.save(output_path)
        return output_path
